//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventologyEntities : DbContext
    {
        public eventologyEntities()
            : base("name=eventologyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chatrooms> chatrooms { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<incidences> incidences { get; set; }
        public virtual DbSet<inventory_items> inventory_items { get; set; }
        public virtual DbSet<inventory_rooms> inventory_rooms { get; set; }
        public virtual DbSet<media> media { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<seats> seats { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
