//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventologyEntities : DbContext
    {
        public eventologyEntities()
            : base("name=eventologyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chatrooms> chatrooms { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<incidences> incidences { get; set; }
        public virtual DbSet<inventory_items> inventory_items { get; set; }
        public virtual DbSet<inventory_rooms> inventory_rooms { get; set; }
        public virtual DbSet<media> media { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<seats> seats { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
