//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_rooms
    {
        public int room_id { get; set; }
        public int inventory_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual inventory_items inventory_items { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
