//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public int sender_id { get; set; }
        public int chat_id { get; set; }
    
        public virtual chatrooms chatrooms { get; set; }
        public virtual users users { get; set; }
    }
}
