//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public int sender_id { get; set; }
        public int chat_id { get; set; }
    
        public virtual chatrooms chatrooms { get; set; }
        public virtual users users { get; set; }
    }
}
