//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tickets()
        {
            this.incidences = new HashSet<incidences>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> reservation { get; set; }
        public string status { get; set; }
        public int buyer_id { get; set; }
        public int event_id { get; set; }
        public Nullable<int> seat_id { get; set; }
    
        public virtual events events { get; set; }
        public virtual seats seats { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incidences> incidences { get; set; }
    }
}
